name: Update version tag 
on:
    push:
      branches: 
      - "main"
env:
    offset_const: 10
jobs:
  Update-Job:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Setup Java
       uses: actions/setup-java@v4
       with: 
         distribution: 'corretto'
         java-version: 17
     - name: Update version tag
       uses: chkfung/android-version-actions@v1.2.2
       with:
         gradlePath: app/build.gradle.kts 
         versionCode: ${{ github.run_number + env.offset_const }}
         versionName: "1.0.10"
     - name: Commit & Push changes
       uses: actions-js/push@v1.5
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}